[package]
name = "chip8emu"
version = "0.1.0"
authors = ["Mason Osborn <mason.osborn@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.21"
byteorder = "1"
serde_json = "1.0.87"
maplit = "1.0.2"
rand = "0.8.5"
enum-primitive-derive = "0.2.2"
num-traits = "0.2.15"
